### ISSUE TITLE
1.配置管理

### ISSUE THREAD

**Issue by humbleDong** [humbleDong/spring-boot-study-practice#1]
# SpringBoot3.x学习

#### @Configuration

```java
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Configuration
@Indexed
public @interface SpringBootConfiguration {
    @AliasFor(
        annotation = Configuration.class
    )
    boolean proxyBeanMethods() default true;
}
```

使用`@Configuration`可以自定义配置类

#### @Import

```java
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Import {
    //可以导入@Configuration，ImportSelector，ImportBeanDefinitionRegistrar或者任何一个Component组件
    Class<?>[] value();
}
```

用来处理配置类在其他子包或者在依赖jar包中，进行配置导入

#### @ImportResource

如果需要导入XML配置可以使用`@ImportResource`

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
@Documented
public @interface ImportResource {
    @AliasFor("locations")
    String[] value() default {};

    @AliasFor("value")
    String[] locations() default {};

    Class<? extends BeanDefinitionReader> reader() default BeanDefinitionReader.class;
}
```

使用方式就是直接指定要导入的XML配置文件路径即可

#### application

SpringBoot应用的配置参数主要在application中

`StandardConfigDataLocationResolver`源码中定义

```java
static final String CONFIG_NAME_PROPERTY = "spring.config.name";
static final String[] DEFAULT_CONFIG_NAMES = new String[]{"application"};
```

**注：它可以有不同形式的配置方式，该配置文件不是必需的，可以有多个，也可以一个都没有**

#### bootstrap

属于SpringCloud环境，需要引入SpringCloud依赖。

bootstrap配置文件会优先于application配置文件被加载

#### 配置文件类型

.properties：key=value格式

.yml：key：value树状格式(yaml)

注：.yml配置文件不支持通过`@PropertySource`注解来导入配置

#### 1.3.1	Spring中的配置绑定

`@PropertySource`注解绑定配置

准备一个db.properties

```java
username=root
password=123456
```

```java
@Component
@PropertySource(value = "classpath:db.properties")
public class DbProperties {

    @Value("${username}")
    private String username;
    @Value("${password}")
    private String password;

    //有/无参构造，get/set,toString
}
```

测试：

```java
@SpringBootTest
public class Test1 {

    @Autowired
    private DbProperties dbProperties;

    @Test
    public  void test(){
        System.out.println(dbProperties);
    }
}
```

结果：

```txt
DbProperties{username='Administrator', password='123456'}
```

**注：因为@PropertySource注解并不支持主流的.yaml配置文件绑定，本身也要结合@Value注解使用，不推荐这种方式**

**但是可以用`@ConfigurationProperties`来实现，具体可以参照[.yaml注入配置](https://gh.qisui.xyz/undefined/e20c50ed.html#4-4注入配置文件)，它同时支持这两种文件格式。**

#### 1.3.2	参数绑定

通过javabean提供的setter方法进行配置参数与Java Bean字段的绑定，首先在application.yaml配置文件中加入person.*配置参数

```yaml
person:
  name: ldd
  age: 18
  happy: true
  birth: 2023/4/13
  maps: {k1: v1, k2: v2, k3: v3}
  lists:
    - sing
    - play
    - music
  db-properties:
    username: root
    password: 123456
```

在person实体类中进行参数绑定

```java
@Component
@ConfigurationProperties(prefix = "person")
public class Person {
    private String name;
    private Integer age;
    private Boolean happy;
    private Date birth;
    private Map<String,Object> maps;
    private List<Object> lists;
    private DbProperties dbProperties;
    
    //有/无参构造，get/set,toString
}
```

测试:

```JAVA
@Autowired
private Person person;

@Test
public  void testPerson(){
    System.out.println(person);
```

结果：

```txt
Person{
name='ldd', 
age=18, 
happy=true,
birth=Thu Apr 13 00:00:00 CST 2023,
maps={k1=v1, k2=v2, k3=v3}, 
lists=[sing, play, music], 
dbProperties=DbProperties{username='root1', password='123456'}}
```

通过`@ConfigurationProperties(prefix = "xxx")`注解绑定配置参数需要用到类的setter方法，该注解可以将配置参数映射到Java Bean上，该注解中的prefix或者value参数用于指定要映射的参数前缀，前缀格式为英文小写，多个前缀以"-"分割如上面db-properties

总结(@ConfigurationProperties)：

- 支持按配置参数前缀绑定参数，前缀一样的参数的配置参数将被绑定到同一个类上
- 支持配置参数使用默认值，如果happy=true,不设置，那么就会输出默认值false
- 支持松绑定，也就是连接符位置可以是“-”，也可是“_”
- 支持Java集合绑定，例如Map，List
- 支持嵌套类，例如dbProperties嵌套了一个类
- 支持主要的配置途径，比如：.yaml文件、.properties文件....
- 可以搭配`@EnableConfigurationProperties`来使用

#### 1.3.3	构造器绑定

需@EnableConfigurationProperties在注解中添加对应的class对象

如果使用构造器绑定时不想使用ConstructorBinding构造器绑定方法，可以使用@Autowired注解代替跟上面一样

弊端：Date这种数据类型无法解决

#### 1.3.4	Bean配置绑定

好处：不需@EnableConfigurationProperties在注解中添加，直接返回一个bean给CommandLineRunner使用即可

弊端：Date这种数据类型无法解决

#### 1.3.5	参数类扫描

如果忘掉在@EnableConfigurationProperties进行注解指定，那么你配置的参数类就不会生效，于是直接提出了一个可以扫描包的方式

在启动类上使用`@EnableConfigurationPropertiesScan`，既可以扫描这个包目录下的所有配置参数类

#### 1.3.6	配置验证

使用了`@EnableConfigurationProperties`还可以进行参数验证

SpringBoot中可以用JSR-303中@validation来校验数据

1.导入JSR-303的依赖

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
```

2.需求

```java
public class Person {
    //我们现在希望name是一个邮箱
    @Email(message = "大哥，请你输入一个正确的邮箱！")//需要导入import org.springframework.validation.annotation.Validated;包
    private String name;
```

3.结果：

直接报错且打印消息

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'person' to com.ldd.pojo.Person failed:

报错如下：

```txt
Property: person.name
Value: "ldd"
Origin: class path resource [application.yaml] - 2:9
Reason: 大哥，请你输入一个正确的邮箱！
```

4.常见的一些参数：

```java
@NotNull(message="名字不能为空")
private String userName;
@Max(value=120,message="年龄最大不能查过120")
private int age;
@Email(message="邮箱格式错误")
private String email;

空检查
@Null       验证对象是否为null
@NotNull    验证对象是否不为null, 无法查检长度为0的字符串
@NotBlank   检查约束字符串是不是Null还有被Trim的长度是否大于0,只对字符串,且会去掉前后空格.
@NotEmpty   检查约束元素是否为NULL或者是EMPTY.
    
Booelan检查
@AssertTrue     验证 Boolean 对象是否为 true  
@AssertFalse    验证 Boolean 对象是否为 false  
    
长度检查
@Size(min=, max=) 验证对象（Array,Collection,Map,String）长度是否在给定的范围之内  
@Length(min=, max=) string is between min and max included.

日期检查
@Past       验证 Date 和 Calendar 对象是否在当前时间之前  
@Future     验证 Date 和 Calendar 对象是否在当前时间之后  
@Pattern    验证 String 对象是否符合正则表达式的规则

.......等等
除此以外，我们还可以自定义一些数据校验规则
```

#### 1.4.1	配置源

即SpringBoot可以将配置外部化，不仅可以把配置放在应用配置文件中，还可以使用各种外部配置源

例如：

- properties文件
- yaml文件
- 环境变量
- 命令行参数

#### 1.4.2	配置优先级

如果多个配置源的参数值相同，则优先级高的参数值最够会覆盖优先级低的参数值

- 配值源优先级(从低到高)：
  1. 默认参数（SpringApplication.setDefaultProperties）
  2. 使用@PropertySource注解绑定的参数
  3. 应用配置文件中的参数（application）
  4. 配置了random.*随机数的参数
  5. 系统环境变量
  6. Java System Properties
  7. java:comp/env的JNDI参数
  8. ServletContext初始化参数
  9. ServletConfig初始化参数
  10. 来自SPRING_APPLICATION_JSON参数
  11. 命令行参数
  12. 单元测试上的参数
  13. 使用@TestPropertySource注解绑定的配置
  14. Devtools全局设置参数(来自$HOME/.config/spring-boot)
- 多个应用配置文件(application)的优先级(从低到高)
  1. 应用配置文件(jar包内)
  2. 指定了profile的配置文件，如application-dev.properties（jar包内）
  3. 应用配置文件(jar包外)
  4. 指定了profile的配置文件，如application-dev.properties（jar包外）

**注：建议整个应用只用一种格式，如果同一个位置有.properties还有.yaml，Springboot会优先采用.properties**

#### 1.4.3	命令行参数

命令行参数指java-jar --key=value命令启动应用时指定的参数，即以“--”开头的参数

例如：
```bash
java -jar demo.jar --server.prot=9090
```

根据优先级，命令行参数的优先级始终是高于配置文件的，这种时候，端口就变为了9090而不是配置文件中的8080或者其他端口

注：默认情况，SpringBoot会将所有命令行参数转换并添加到Spring环境中，如果不想添加到Spring环境中，可以在主启动类中将其禁用。

```java
public static void main(String[] args) {
    SpringApplication.setAddCommandLineProperties(false);
    SpringApplication.run(SpringBootQuickStartApplication.class, args);
}
```

### 1.5	导入配置

可以使用`spring.config.import`参数来指定要导入的配置文件路径

```yaml
spring:
  config:
    import:
      -optional:classpath:/config/app.yml
```

这里就指定了要导入一个app.yml配置文件

```yaml
person:
  happy: false
```

去测试：

开始我们的happy现在就是false了

![image-20231204175925395](./image/image-20231204175925395.png)

### 1.6	随机值配置

SpringBoot提供了RandomValuePropertySource类可以用于注入随机值，它可以生成整数(int)、长整数(long)、UUID及字符串

修改一下.yaml配置文件

```yaml
person:
  #${random.value}和${random.uuid}生成的是32位MD5字符串
  name: ldd 随机uuid:${random.uuid},随机value:${random.value},随机int:${random.int(1,10)}
  age: 18
  happy: true
  birth: 2023/4/13
  maps: {k1: v1, k2: v2, k3: v3}
  lists:
    - sing
    - play
    - music
  db-properties:
    username: root
    password: 123456


spring:
  config:
    import:
      - optional:classpath:/config/app.yml
```

测试：

```txt
Person{name='ldd 
随机uuid:bc3997f2-0227-46fb-b0de-92ca5b32e30a,
随机value:567c0721b75977ff8fc499348fff1706,
随机int:5,......
```

**注：底层就是使用了Java自带的java.util.Random和java.util.UUID工具类**

#### 1.7.1	配置格式

- .yaml配置文件多文档之间用三个连接符(---)进行分隔开
- .properties配置多个文件用#---分隔

例如：

.yaml

```yaml
spring:
  application:
    name: "dev"
      
---
spring:
  application:
    name: "dev-cloud"
  config:
    activate:
      on-cloud-platform: "kubernetes"

```

.propreties

```properties
spring.application.name=dev
#---
spring.application.name=dev-cloud
spring.config.activate.on-clound-platform=kubernetes
```

***注*：**

- **使用多文档配置需要注意：**
  1. **多文档配置的分隔符前面不能有空格，并且分隔符要连续**
  2. **多文档配置的分隔符前、后一行不能是注释**
  3. **多文档配置不能被@PropertySource和TestPropertySource注解加载**

#### 1.7.2	激活多文档配置

| 激活参数                                  | 说明                  |
| ----------------------------------------- | --------------------- |
| spring.config.activate.on-clound-platform | 根据指定的云平台激活  |
| spring.config.activate.on-profile         | 根据指定的Profile激活 |

```yaml
person:
  #${random.value}和${random.uuid}生成的是32位MD5字符串
  name: ldd 随机uuid:${random.uuid},随机value:${random.value},随机int:${random.int(1,10)}
  age: 18
  happy: true
  birth: 2023/4/13
  maps: {k1: v1, k2: v2, k3: v3}
  lists:
    - sing
    - play
    - music
  db-properties:
    username: root
    password: 123456


spring:
  config:
    import:
      - optional:classpath:/config/app.yml
  application:
    name: "dev"
  profiles:
    active: dev

---
spring:
  application:
    name: "dev-cloud"
  config:
    activate:
      on-cloud-platform: "kubernetes"

---
spring:
  config:
    activate:
      on-profile: "dev | test"
```

像这样，通过spring.profiles.active激活了dev环境

但是第三个配置文档只在dev和test环境中生效

#### 1.8.1	默认的Profile

如果不指定要激活的Profile，SpringBoot会使用默认的Profiledefault配置，启动日志即可看到

```txt
No active profile set, falling back to 1 default profile: "default"
```

也可以调整默认的Profile

```yaml
spring:
  prpfiles:
    default: dev
```

#### 1.8.2	激活Profile

可以使用spring.profiles.active参数指定要激活的Profile

```yaml
server:
  port: 8081
#选择要激活那个环境块
spring:
  profiles:
    active: prod

---
server:
  port: 8083
spring:
  profiles: dev #配置环境的名称
  
---

server:
  port: 8084
spring:
  profiles: prod  #配置环境的名称
```

此时prod环境就被激活了

也可以在应用方法上进行激活

```java
@SpringBootApplication
public class SpringBootQuickStartApplication {
    public static void main(String[] args) {
		SpringApplication springApplication = new SpringApplication(SpringBootQuickStartApplication.class);
        springApplication.setAdditionalProfiles("dev");
        springApplication.run(args);
//        SpringApplication.run(SpringBootQuickStartApplication.class, args);  
    }
}
```

Profile不仅可以激活配置文件，还可以激活Java配置类，比如可以用在@Componet、@Configuration或者@ConfigurationProperties注解的类上

#### 1.8.3	切换Profile

命令行

```bash
java -jar demo.jar --spring.profiles.active=test
```

IDE

```mvn
mvn spring-boot:run -Dapp.profiles=test
```

当然如果不想被优先级更高的配置源替换，也可以使用`spring.profiles.include`附加模式

#### 1.8.4	profile分组

spring.profiles.group

#### 1.8.5	指定profile配置文件

比如多个配置文件：

- application.yaml
- application-dev.yaml
- application-test.yaml
- application-prod.yaml
- application-main.yaml

优先级：

`默认>dev>main`

#### 1.8.6	使用限制

| 参数                    | 功能                    | 说明                                  |
| ----------------------- | ----------------------- | ------------------------------------- |
| spring.profiles.default | 指定默认的Profile       | 当不指定Profile时，默认生效的Profile  |
| spring.profiles.active  | 激活指定的Profile       | 可以被优先级高的配置源替换            |
| spring.profiles.include | 激活指定要包含的Profile | 不会被其他配置源替换                  |
| spring.profiles.group   | 指定Profile分组         | 激活一个分组，就会激活组下所有Profile |

**注：以上几个参数不能用于多文档配置中和指定Profile配置文件**

### 1.9	加载机制

SpringBoot中的配置文件是通过PropertySourceLoader接口实现的：

```java
public interface PropertySourceLoader {
    String[] getFileExtensions();

    List<PropertySource<?>> load(String name, Resource resource) throws IOException;
}
```

- getFileExtensions()：获取文件后缀
- load：加载配置

该接口下有两个实现类

- YamlPropertySourceLoader
- PropertiesPropertySourceLoader

![image-20231205100157009](./image/image-20231205100157009.png)

一句话概括一下：SpringBoot启动时候发布事件，然后通过注册监听器监听，监听器听到时间后就立马加载指定路径的配置文件
